Updated download script to use sha from repository

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -127,7 +127,7 @@ jobs:
         shell: bash
         env:
           OS: 'Windows'
-          ARCH: 'X64'  
+          ARCH: 'X64'
         run: |
           ./scripts/configure_paths.sh > output
           grep -v "::error::" output
@@ -147,7 +147,7 @@ jobs:
         shell: bash
         env:
           OS: 'Linux'
-          ARCH: 'X64'  
+          ARCH: 'X64'
         run: |
           ./scripts/configure_paths.sh > output
           grep -v "::error::" output
@@ -167,7 +167,7 @@ jobs:
         shell: bash
         env:
           OS: 'macOS'
-          ARCH: 'X64'  
+          ARCH: 'X64'
         run: |
           ./scripts/configure_paths.sh > output
           grep -v "::error::" output
@@ -187,7 +187,7 @@ jobs:
         shell: bash
         env:
           OS: 'unsupportedOS'
-          ARCH: 'X64'  
+          ARCH: 'X64'
         run: |
           (./scripts/configure_paths.sh  || echo "=== Script failed ===") > output
 
@@ -199,7 +199,7 @@ jobs:
         shell: bash
         env:
           OS: 'Linux'
-          ARCH: 'X86'  
+          ARCH: 'X86'
         run: |
           (./scripts/configure_paths.sh  || echo "=== Script failed ===") > output
 
@@ -219,29 +219,24 @@ jobs:
       - name: Download test without validation
         shell: bash
         env:
-          INSTALL_PATH: 'install-directory'
+          INSTALL_PATH: 'install-directory-no-sha-validation'
           DOWNLOAD_URL: 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip'
-          SHA_DOWNLOAD_URL: 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip.sha256'
+          DOWNLOAD_SHA: 'incorrect-sha-not-validated'
           TMP_ZIP_PATH: ${{ runner.temp }}/sonar-scanner.zip
         run: |
           ./scripts/download.sh > output
           test -f "$TMP_ZIP_PATH"
-          if [ -f "$TMP_ZIP_PATH.sha256" ]; then
-            echo "$TMP_ZIP_PATH.sha256 shouldn't exist"
-            exit 1
-          fi
           grep -v "::error::" output
       - name: Download test with validation
         shell: bash
         env:
           INSTALL_PATH: 'install-directory-sha-validation'
           DOWNLOAD_URL: 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip'
-          SHA_DOWNLOAD_URL: 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip.sha256'
+          DOWNLOAD_SHA: '9411331814c1d002bd65d37758b872918b7602e7cf3ca5b83a3e19a729b2be05'
           TMP_ZIP_PATH: ${{ runner.temp }}/sonar-scanner.zip
         run: |
           ./scripts/download.sh -v > output
           test -f "$TMP_ZIP_PATH"
-          test -f "$TMP_ZIP_PATH".sha256
           grep -v "::error::" output
       - name: Incorrect install dir
         shell: bash
@@ -254,22 +249,33 @@ jobs:
       - name: Incorrect download url
         shell: bash
         env:
-          INSTALL_PATH: 'install-directory'
+          INSTALL_PATH: 'install-directory-incorrect-url'
           DOWNLOAD_URL: 'incorrect-url'
         run: |
           (./scripts/download.sh || echo "=== Script failed ===") > output
           grep "::error::Failed to download 'incorrect-url'" output
           grep "=== Script failed ===" output
-      - name: Incorrect SHA256 url
+      - name: Incorrect SHA256
         shell: bash
         env:
-          INSTALL_PATH: 'install-directory'
+          INSTALL_PATH: 'install-directory-incorrect-sha'
           DOWNLOAD_URL: 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip'
-          SHA_DOWNLOAD_URL: incorrect-sha256-url
+          DOWNLOAD_SHA: 'incorrect-sha256'
           TMP_ZIP_PATH: ${{ runner.temp }}/sonar-scanner.zip
         run: |
           (./scripts/download.sh -v || echo "=== Script failed ===") > output
-          grep "::error::Failed to download 'incorrect-sha256-url'" output
+          grep "::error::Checking sha256 failed" output
+          grep "=== Script failed ===" output
+      - name: Mismatching SHA256
+        shell: bash
+        env:
+          INSTALL_PATH: 'install-directory-mismtaching-sha'
+          DOWNLOAD_URL: 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip'
+          DOWNLOAD_SHA: '3e121d85a4adb1f30b917d5f3eb897966b59e02c3d6d313a78dcd964193dc963'
+          TMP_ZIP_PATH: ${{ runner.temp }}/sonar-scanner.zip
+        run: |
+          (./scripts/download.sh -v || echo "=== Script failed ===") > output
+          grep "::error::Checking sha256 failed" output
           grep "=== Script failed ===" output
 
   output-test:
